const app={clientes:[],mapa:null,marcadores:[],clienteSelecionado:null};
document.addEventListener('DOMContentLoaded',async()=>{configurarAbas();configurarFiltros();inicializarMapa();await pesquisarReal();atualizarDashboard()});
function inicializarMapa(){if(!window.L)return;app.mapa=L.map('mapa').setView([-23.5505,-46.6333],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(app.mapa)}
async function pesquisarReal(){const cidade=prompt('Cidade para prospecção','São Paulo');if(!cidade)return;const tipo=document.getElementById('filtro-tipo')?.value||'acupuntura';const r=await fetch('/api/pesquisa',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cidade,tipo})});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Falha na pesquisa');app.clientes=d.clientes||[];renderizarClientes();atualizarMapa();atualizarDashboard()}
function atualizarMapa(){if(!app.mapa)return;app.marcadores.forEach(m=>m.remove());app.marcadores=[];app.clientes.forEach(c=>{const m=L.circleMarker([c.latitude,c.longitude],{radius:9,fillColor:c.potencial==='alto'?'red':c.potencial==='medio'?'orange':'green',color:'#fff',weight:2,fillOpacity:.8}).bindPopup(`<b>${escapeHtml(c.nome)}</b><br>${escapeHtml(c.endereco||'')}<br><a href="${c.website||'#'}" target="_blank">Site</a>`).addTo(app.mapa);app.marcadores.push(m)})}
function renderizarClientes(){const el=document.getElementById('lista-clientes');if(!el)return;const tipo=document.getElementById('filtro-tipo')?.value||'',pot=document.getElementById('filtro-potencial')?.value||'';const list=app.clientes.filter(c=>(!tipo||c.tipo===tipo)&&(!pot||c.potencial===pot));el.innerHTML=list.length?list.map(c=>`<div class="card"><div class="card-header"><div><h3 class="card-titulo">${escapeHtml(c.nome)}</h3><p>${escapeHtml(c.endereco||'')}</p></div><span class="badge ${c.potencial}">${c.potencial}</span></div><div class="info"><div class="info-item"><b>Tipo:</b> ${escapeHtml(c.tipo||'')}</div><div class="info-item"><b>Telefone:</b> ${escapeHtml(c.telefone||'Não informado')}</div><div class="info-item"><b>Fonte:</b> OpenStreetMap</div></div><div class="btn-grupo">${c.telefone?`<a class="btn btn-secundario btn-pequeno" href="tel:${encodeURIComponent(c.telefone)}">📞 Chamar</a>`:''}${c.website?`<a class="btn btn-primario btn-pequeno" target="_blank" href="${encodeURI(c.website)}">🌐 Site</a>`:''}<button class="btn btn-sucesso btn-pequeno" onclick="analisar('${c.id}')">🧠 Analisar com IA</button></div><div id="ia-${c.id}" style="margin-top:10px"></div></div>`).join(''):'<div class="empty">Nenhum estabelecimento encontrado. Faça uma nova pesquisa.</div>'}
async function analisar(id){const c=app.clientes.find(x=>x.id===id),el=document.getElementById(`ia-${id}`);el.innerHTML='Analisando...';const r=await fetch('/api/analisa',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cliente:c})});const d=await r.json();el.innerHTML=r.ok?`<div class="notice"><b>Análise IA</b><pre style="white-space:pre-wrap">${escapeHtml(JSON.stringify(d.analise,null,2))}</pre></div>`:`<div class="notice">${escapeHtml(d.error||'Erro na análise')}</div>`}
function configurarAbas(){document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('ativo'));document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('ativo'));b.classList.add('ativo');document.getElementById(b.dataset.aba)?.classList.add('ativo');if(b.dataset.aba==='aba-mapa')setTimeout(()=>app.mapa?.invalidateSize(),100)}))}
function configurarFiltros(){document.getElementById('filtro-tipo')?.addEventListener('change',renderizarClientes);document.getElementById('filtro-potencial')?.addEventListener('change',renderizarClientes)}
function atualizarDashboard(){const s=document.getElementById('stats');if(!s)return;const n=x=>app.clientes.filter(c=>c.status===x).length;s.innerHTML=`<div class="stat-box"><div class="stat-numero">${app.clientes.length}</div><div class="stat-label">Leads encontrados</div></div><div class="stat-box"><div class="stat-numero">${n('novo')}</div><div class="stat-label">Novos</div></div><div class="stat-box"><div class="stat-numero">${app.clientes.filter(c=>c.telefone).length}</div><div class="stat-label">Com telefone</div></div>`}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function carregarRanking(){document.getElementById('resultado-ia').innerHTML='<div class="card">Use “Analisar com IA” em cada lead encontrado para gerar ranking e abordagem.</div>'}
async function carregarProximasAcoes(){document.getElementById('resultado-ia').innerHTML='<div class="card">Primeiro faça uma pesquisa real e analise os leads prioritários.</div>'}
function listarPorStatus(status){document.getElementById('resultado-crm').innerHTML=`<div class="card">${app.clientes.filter(c=>c.status===status).length} lead(s) com status <b>${status}</b>.</div>`}
function mostrarProximasAcoes(){listarPorStatus('novo')}
function buscarPorRaio(){document.getElementById('resultado-raio').innerHTML='<div class="notice">A pesquisa usa dados geográficos reais do OpenStreetMap. Faça uma nova pesquisa para alterar a região.</div>'}